services:
  -type: web
  name: IDR-Small-Project-Bodan
  env: python
  plan: free

  buildCommand: "pip install -r requirements.txt"

  startCommand: "gunicorn --chdir src app:server"

  envVars:
    -key: PYTHON_VERSION
    value: 3.8
